### ISSUE TITLE
LS1 Script Connectivity Issues

### ISSUE THREAD

**Issue by cflottorp** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#110]
Connectivity issues running with the LS1 FIT server script for Admin Tool when the iPad app has been installed. Possible communication issue between nodejs and Apache during the initialization of the  Admin Tool configuration.  Logfile with error will be sent to assist in the investigation process.

**Comment by callmekatootie** [comment]
@rsial2 You have wrongly tagged me here

**Comment by rsial2** [comment]
Sorry @callmekatootie, I will fix this.

**Comment by coderReview** [comment]
@cflottorp I didn't understand this issue. iPad application does not need admin tool running to work. Only Postgresql database server.

**Comment by cflottorp** [comment]
Something happened between when the script was run setting up the database server and when we wanted to input the data using the Admin tool.  Since both the Admin Tool and our App Portal are on the same server and they use Apache and that we couldn't access them afterwards.  We thought there was an permission or connectivity issue with Apache when the script was run.  we also noticed that nodejs thought there was already a nodejs session running after we re-booted which should have killed the session or generated a new one.

**Comment by briandmartin** [comment]
I installed the FIT Admin Tool on ls1 and it was running.  I could access the Admin Tool from a browser it looked fine.  I moved ls1 to another lab and then the FIT Admin Tool would no longer run.  Nothing happened in between that time.  Just a few reboots.  The Node.JS init.d script reported it was running but the webpage would not serve and the FIT iPad app would not run.  I don't know what the issue is.  I believe Cheryl should have sent you the logs.

**Comment by rsial2** [comment]
@coderReview - please see the feedback above. Please confirm that you've reviewed the logs as well.

**Comment by coderReview** [comment]
The nodejs script was updated. Now it is starting correctly during boot. Was the test done wih the new version of the script?
Run 'ps ax|grep node' to be sure the admin tool is running.

**Comment by briandmartin** [comment]
Below is the the md5 checksum of the version of nodejs init.d script we tested with.

Tomorrow at 09:00 AM Central, the Payloads team is coming to the SSC Lab to test FIT.  Today, I'm doing the ls1 FIT install to prepare for their test.  The "ps ax|grep node" suggestion is helpful, thanks I'll note that.  However, the ls1 we tested FIT on last time has been reloaded to fajita configuration to prepare for the 09:00 test tomorrow.  The reload is in work so I cannot still provide you the result of that command at this time.  But noted for future, thanks.

node-0.10.29-release.zip  nodejs                    
[ ~/ssc_system/switched/linux/build_record_ls1/service_pack/fajita/other_files ]:
bdmarti1@mslhost>$ md5sum nodejs 
1a8cd7403d09f8fc9b31d1dc83bc84a8  nodejs
[ ~/ssc_system/switched/linux/build_record_ls1/service_pack/fajita/other_files ]:
bdmarti1@mslhost>$

**Comment by rsial2** [comment]
Thanks Brian. We will wait to hear back from you regarding the deployment with the new script.

**Comment by rsial2** [comment]
@briandmartin how did the re-test go?

**Comment by cflottorp** [comment]
The FIT Admin Tool appears to accept imports of food data and user data.  However we have a problem with Apache after loading FIT server script,  Apache is crashing and seems to be over taking all other app machine to machine account authentications.  All other apps on the iPad receive a HTTP 401 error and we couldn't access them afterwards. Previous authentications and passwords were broken. All other ipad app authentication fail; it appears that FIT userid is needed but fails with password. Error logs will be sent in another e-mail.

**Comment by briandmartin** [comment]
@rsial2 @coderReview I made two changes to the FIT install script.  I gave a copy to @cflottorp and she's going to send you two the script.  
1.) Change from:
SP_BACKUP=/admin/enchilada
to:
SP_BACKUP=/admin/fajita

This was because the FIT integration is being scheduled for fajita SP and no longer in the enchilada SP.


2.) I commented out these two lines of code: 

#usermod -a -G sasl ${ACCT}
#echo ${ACCT}:${ACCT_ADMIN_PASSWD} | chpasswd


The SSC Account Management Tool (AMT) builds the "pl_fit" Machine-to-machine account.  These commands are sufficient for your testing, but the AMT is what will actually create that account and not the script.  We have documentation on AMT we could send you if you wanted to learn how to use it to build an Account Package to create accounts.  But, that's not required and the two commands in the script are sufficient for your testing.  But we need to leave them commented out so they don't get run on-orbit.

**Comment by coderReview** [comment]
@briandmartin ok. You just need to set the pl_fit account password to the one generated by the script. I will look into the logs to see if I can find ot what is causing the issues with apache.

**Comment by briandmartin** [comment]
@coderReview actually, both the "usermod" and "echo ... | chpasswd" commands are commented out so the script doesn't actually create the account or set its password.  Both of those two steps are handled by AMT.  Of course, like I said, you can just uncomment them out to test and that's fine and you don't have to have AMT on your dev/test instance.

**Comment by coderReview** [comment]
@briandmartin Please change the line 1 in file /etc/apache2/sites-available/pl_fit-ssl to look like this:
<VirtualHost *:443>

If that solves the issue I will update the fit script and send it to @rsial2.

**Comment by briandmartin** [comment]
@cflottorp @coderReview @rsial2 Yes, that did work!  All 3 apps I tested worked in that config: FIT, Portal and iSHORT.
